### ISSUE TITLE
Speed Mode

### ISSUE THREAD

**Issue by jfejfe** [TCWORLD/gLCD-Library#2]
Hello, I'm trying to use the speed mode on the fourth version of the library with an arduino UNO and a nokia LCD shield.
I'm usin this pin set up:

const char RST = 7;
const char Dat = 6;
const char Clk = 5;
const char CS = 4;

and the only change I do is this:
gLCD graphic(RST,CS,Clk,Data,1); // gLCD graphic(RST,CS,Clk,Data,0)

When it's not on speed mode, LCD works perfectly, but whe I change it, it seems that only the backlight works.
The test pattern work fine also.

**Comment by TCWORLD** [comment]
I am having a look at the code, but I dont see anything wrong with it. How have you wired the display - is it directly connected or are there lots of long wires like on a breadboard. The reason I ask is that it is possible that the highspeed mode is running so fast that data being send is getting corrupted by the wiring.
As far as I can tell the code works fine. I haven't tried every combination of pins, but I see no reason why the ones you chose wouldn't work.
I will keep looking for a programming error, but can I suggest you try wiring the display with shorter cables, and try putting a small 100nF or similar capacitor on its power supply, then report back as to if it works.

Another test you could do for me would be to add:

delayMicroseconds(2);

at the end of each of these functions in the gLCD.cpp file:

void gLCD::writeRS(boolean bitValue){
     ...
}

void gLCD::writeCS(boolean bitValue){
     ...
}

void gLCD::writeSCLK(boolean bitValue){
     ...
}

void gLCD::writeSDATA(boolean bitValue){
     ...
}

doing so will slightly slow the highspeed mode down and might be enough that you can still benefit from a speed increase.

**Comment by TCWORLD** [comment]
I have checked the registers and bit masks that the library produces for the pins you chose for an arduino Uno, and they are correct (rs = PD7, data = PD6, clk = PD5, cs = PD4)

**Comment by jfejfe** [comment]
I put the capacitor on 3.3V-GND, a change the pins to:
const char RST = 11;
const char Dat = 10;
const char Clk = 9;
const char CS = 8;

and also I include in each function:  
delayMicroseconds(2);

and the speed mode works.
Actually it works before  I do the changes,  but I need to be able to use other pins, because I want to use a microSD module too.

**Comment by jfejfe** [comment]
The entire code is this:

#include <gLCD.h>

const char RST = 7;
const char Dat = 6;
const char Clk = 5;
const char CS = 4;

gLCD graphic(RST,CS,Clk,Dat,1); //Speed Mode

void setup(){
  graphic.Init(1,1,0,1,1);
}
void loop(){
  graphic.testPattern();
  while(1);
}

**Comment by TCWORLD** [comment]
Does it work on the old pins (7,6,5,4) with the delays added to each of the functions mentioned earlier?

**Comment by jfejfe** [comment]
It doesn't work with the delays added.
(I'm using Arduino UNO and arduino1.0)

**Comment by TCWORLD** [comment]
In arduino, would you be able to go to:
File->Preferences, and check the box which says 'Compilation' next to 'show verbose output'. Then click OK.

Then compile the testPattern example (by clicking on the Tick button).
At the bottom of the screen, there will be lots of which text, the last couple of lines will show a directory (something like C:\Users...\AppData\Local\Temp\build.......tmp
Would you be able to open that directiory and send me the file called "TestPattern.cpp.elf". If you could send it to:
other (at) railways-in-miniature (dot) co (dot) uk

**Comment by jfejfe** [comment]
I've already send the file.
Thanks you for your help.

**Comment by jfejfe** [comment]
The LCD it's now working.
I will send you the file (sketchfile.cpp.elf).
I remove the delays,  and also I remove the old directory of the gLCD library (It was named old_gLCD).
Thanks you very much for the help.

**Comment by TCWORLD** [comment]
Ahh, that suggests that arduino was trying to compile the old library which didn't automatically calculate the correct pins. Glad the problem is solved.

**Comment by jfejfe** [comment]
Maybe that was the problem, but before I put the new version of the library, I rename the file of the old version (old_gLCD).
(should I close the issue)

**Comment by TCWORLD** [comment]
I have closed the issue :)
