### ISSUE TITLE
Window function problem for EPSON driver

### ISSUE THREAD

**Issue by WellsWang** [TCWORLD/gLCD-Library#3]
Hi Tom,

My Nokia 6100 LCD is using EPSON controller.
When I use Plot function to draw 1 pixel, it will draw 2 dots on the screen. one is (x,y), another is (x,y+1) (y is in even number) or (x,y-1) (y is in odd number). 
the page & column config is:
SendByte(_command, 0xBC);            //Display Control
SendByte(_parameter, 0x07);          //Scan direction (left-->right or right-->left)
SendByte(_parameter, 0x00);          //RGB colour order
SendByte(_parameter, 0x02);

After I changed the scan direction to 0x03, switched the page and column, the 2 dots are (x,y) and (x+1,y) or (x-1,y).

Same problem in Line and Box function. Line function will draw a double width line, and the same as Box border.

I think may be the problem is in Window function, but I don't know how to fix it. 
Thanks.

BR,
Wells.

**Comment by WellsWang** [comment]
Hi Tom,

I think may be the problem is describe in this page:
http://www.electricstuff.co.uk/noklcd.html
In this page, it said, 

"The main difference between the Epson 15G00 and 15G10 is that the latter supports a 2 byte->1 pixel 16 bit mode. Note that there are now LCDs (possibly using an Epson clone controller) that don't apear to support the old 3 byte-> 2 pixel modes. 

Only relevant if using 16 bit mode : The 3 byte/2 pixel 16 bit mode (DATCTL with P3=2) does not appear to be supported by the new controller. The 2 byte/1 pixel mode (DATCTL with P3=4), as documented on Loren Blaney's page and in the Epson S1D15G10 datasheet seems to work fine."

I changed the 3rd parameter of DATCTL to 0x04, the program can draw 1 pixel correctly, but the color is incorrect... need to chage the two_pixel function either.

BR,
Wells.

**Comment by WellsWang** [comment]
Hi Tom,

After changed the DATCTL P3 to 0x04, and changed the twoPixels() function to send 4 bytes data for 2 pixels, the problem solved.

Thanks!

BR,
Wells

**Comment by TCWORLD** [comment]
Glad you have a solution. I will integrate the solution into the library for version 3.1.

**Comment by TCWORLD** [comment]
Could you tell me how you formatted the 4bytes of colour? I ask because I don't have an EPSON Screen at the moment, so cant test it out.

**Comment by WellsWang** [comment]
Hi Tom,

You can find it in this file:
http://www.sparkfun.com/datasheets/LCD/S1D15G10D08BE_TM_MF1493_03.pdf

on page 16, "(2-2) Type B 4096 color display, (1) 8 bit mode" section.

0x04 mode - the 2 bytes 1 pixel mode:

> > XXXXRRRR    // first pixel, red value, XXXX is ignored
> > GGGGBBBB    // first pixel, green and blue value
> > XXXXRRRR    // second pixel, red value, XXXX is ignored
> > GGGGBBBB    // second pixel, green and blue value

So I modified the twoPixels() function for my screen:

``` C
void gLCD::twoPixels(byte SendR1, byte SendG1, byte SendB1, byte SendR2, byte SendG2, byte SendB2){
    byte Send00R1 = SendR1;
    byte SendG1B1 = (SendG1 << 4) | (SendB1);
    byte Send00R2 = SendR2;
    byte SendG2B2 = (SendG2 << 4) | (SendB2);

    twoPixels(Send00R1, SendG1B1, Send00R2, SendG2B2);
}

void gLCD::twoPixels(byte Send00R1, byte SendG1B1, byte Send00R2, byte SendG2B2){
    //Add both pixels to the window
    SendByte(_parameter, Send00R1);
    SendByte(_parameter, SendG1B1);
    SendByte(_parameter, Send00R2);
    SendByte(_parameter, SendG2B2);
}

void gLCD::setSendColour(char Colour){
    //Get type for each pixel
    int pixelOne = Colour & 1;
    int pixelTwo = (Colour >> 1) & 1;

    //Pixel data is in the format:   XXXXRRRR GGGGBBBB XXXXRRRR GGGGBBBB, where this is  two pixels worth of data

    //Is pixel one foreground or background
    if (pixelOne){
        _Send00R1 = _ForeRed;
        _SendG1B1 = _ForeGreen << 4;
        _SendG1B1 |= _ForeBlue;
    } else {
        _Send00R1 = _BackRed;
        _SendG1B1 = _BackGreen << 4;
        _SendG1B1 |= _BackBlue;
    }
    //Is pixel two foreground or background
    if (pixelTwo){
        _Send00R2 = _ForeRed;
        _SendG2B2 = _ForeGreen << 4;
        _SendG2B2 |= _ForeBlue;
    } else {
        _Send00R2 = _BackRed;
        _SendG2B2 = _BackGreen << 4;
        _SendG2B2 |= _BackBlue;
    }
}

void gLCD::twoPixels(char Colour){
    setSendColour(Colour);
    //Add both pixels to the window
    twoPixels();
}

void gLCD::twoPixels(){
    //Add both pixels to the window (use the old colour data)
    SendByte(_parameter, _Send00R1);
    SendByte(_parameter, _SendG1B1);
    SendByte(_parameter, _Send00R2);
    SendByte(_parameter, _SendG2B2);
}
```

FYI,

Thanks!

BR,
Wells.

**Comment by WellsWang** [comment]
Hi Tom,

I'm very glad to help you for testing v3.1, since you don't have the EPSON screen. :)
Thanks.

BR,
Wells.

**Comment by TCWORLD** [comment]
I have almost finished making some changes. They go a lot deeper than what you have done as it has to support both screens whilst not seeing a reduction in performance.
I cant just change it for all EPSON screens as all the ones I have used in the past have not supported the 16bit mode - or at least I couldn't make them accept it, otherwise I would only be sending one pixel at a time rather than two.

**Comment by TCWORLD** [comment]
Could you try this:
http://www.railways-in-miniature.co.uk/electronics/gLCD.zip

In the  begin(...); call, use EPSON_5

**Comment by WellsWang** [comment]
Hi Tom,

I've tried the new library, it works fine! Great!!!
Thanks for your help!

BR,
Wells.

**Comment by TCWORLD** [comment]
Glad to here it. I will do a bit more testing with my Phillips display to make sure that I haven't broken anything, and then I shall release it. Thanks for your help.

This issue is now closed.
