### ISSUE TITLE
Problem writing strings with periods

### ISSUE THREAD

**Issue by pappastech** [TCWORLD/gLCD-Library#4]
I'm trying to display an IP address and several floating point numbers using the gLCD.print method. Printing all other text works as expected except as the examples show below.
## graphic.print( Ethernet.localIP() ); // This prints the last octet at the chosen coordinates

float temp = 23.56;
## graphic.print( temp ); // This prints 63 at the chosen coordinates

float temp = 23.42;
graphic.print( temp ); // This prints 23 at the chosen coordinates

I looked through the library and don't see anything that stands out as a likely cause. Any thoughts you have would be most appreciated.

Thanks for the great work on this library!

Tom

**Comment by TCWORLD** [comment]
I think I have worked out why. Basically, the print(Printable&) and print(float) functions make a series of print() calls themselves. So for example printing a float will first call print on the integer part (23), then on the decimal point print('.'), then on the remainder - print(5), print(6). The result is that you end up seeing:

23
.3 <- after next print, the '.' gets printed at the original coordinate.
53
63 <- final result as you saw

The same will be true for the IP address.

I am working on a bug fix now.

**Comment by TCWORLD** [comment]
The problem should now be solved. Let me know if it fixes if for you.

**Comment by pappastech** [comment]
Did you intend on re-opening this issue?

I'll test the update this evening.

Thanks,
Tom

**Comment by TCWORLD** [comment]
I hadn't intended to reopen it, no. I must have clicked the button accidentally.

**Comment by pappastech** [comment]
Works great...thanks again for the great work on this library!

Tom
