### ISSUE TITLE
Errors while trying to compile example script

### ISSUE THREAD

**Issue by centizen** [TCWORLD/gLCD-Library#5]
Hey there friends; first off let me thank you for all of the work you have done thus far on this project. I was pointed to this project by the comments on sparkfun.

I've got my screen wired up to a Teensy3.0 microcontroller and I'm using Arduino 1.0.2. When I try to compile the testpattern example; I got an error 

```
C:\Users\Michael\Desktop\arduino-1.0.2\libraries\gLCD\gLCD.cpp: In constructor 'gLCD::gLCD(unsigned char, unsigned char, unsigned char, unsigned char, SpeedMode)':
C:\Users\Michael\Desktop\arduino-1.0.2\libraries\gLCD\gLCD.cpp:160: error: 'NOT_A_PIN' was not declared in this scope
```

I went into the .cpp file for the library and tried to find a reference for NOT_A_PIN and couldn't. I tried defining NOT_A_PIN as 0 and then got this error

```
gLCD\gLCD.cpp.o: In function `gLCD::mapWindowCoordinates(int&, int&, int&, int&)':
C:\Users\Michael\Desktop\arduino-1.0.2\libraries\gLCD/gLCD.cpp:347: undefined reference to `__cxa_guard_acquire'
C:\Users\Michael\Desktop\arduino-1.0.2\libraries\gLCD/gLCD.cpp:347: undefined reference to `__cxa_guard_release'
C:\Users\Michael\Desktop\arduino-1.0.2\libraries\gLCD/gLCD.cpp:348: undefined reference to `__cxa_guard_acquire'
C:\Users\Michael\Desktop\arduino-1.0.2\libraries\gLCD/gLCD.cpp:348: undefined reference to `__cxa_guard_release'
collect2: ld returned 1 exit status
```

Any idea's as to what I am doing wrong? I have tried both Phillips and Epson driver codes to no avail. I'd really love to get my screen working. Thanks!

Michael

**Comment by TCWORLD** [comment]
"NOT_A_PIN" is a define in Arduino.h. What it means is that when using high-speed mode, the library cannot identify the pin number you have supplied.

For the pin numbers you are using, try just running a simple program which just calls digitalWrite() on them, does such a sketch compile?

**Comment by TCWORLD** [comment]
Hang on a moment, the Teensy 3 is not an AVR based board, it is an ARM Cortex based one. The ARM based chips use a totally different set of registers and commands.

The library has been ported to work on the ARM chip used by the Arduino Due (the SAM8X), but the Teensy3 uses a completely different ARM chip, with a different architecture and is unsupported by gLCD-Library.

I would have to do some research into the chip used on the Teensy 3 to see if it is possible to port the library to it.

**Comment by centizen** [comment]
Okay, I do have access to Teensy 2's which I can use but they run at 5v and I am unsure if that will damage the board. I don't have any level converters; but if the screen will run off 5v directly then I can try using that. 

Thanks for the quick reply!

Michael

**Comment by TCWORLD** [comment]
Which sparkfun board do you have?

**Comment by centizen** [comment]
LCD-11062

**Comment by TCWORLD** [comment]
You will need level shifting, but for this display that can be as simple as a 1.8k resistor in series with each of the SPI lines (CLK, RST, CS, DIO), and then also a 3.3v voltage regulator for power.
