### ISSUE TITLE
Due Example / diagram

### ISSUE THREAD

**Issue by TheKitty** [TCWORLD/gLCD-Library#6]
It would help alot to see an example using the Arduino Due pins (maybe with a wiring diagram that you used).  Thanks for your consideration, Mike

**Comment by TCWORLD** [comment]
I used the Sparkfun Sheild:
https://www.sparkfun.com/products/9363

Nothing special, just plug in and go. If you need to know how its wired, you can refer to the schematic for the sheild here:
http://www.sparkfun.com/datasheets/DevTools/Arduino/Color-LCD-Shield-v12.pdf

Hopefully that is all the information you should need :)
