### ISSUE TITLE
It seems Sparkfun no longer sells these LCDs

### ISSUE THREAD

**Issue by q2dg** [TCWORLD/gLCD-Library#8]
Have you thought extending hardware support of this library?

**Comment by TCWORLD** [comment]
The library supports pretty much any Nokia 6100 display - doesn't have to be from Sparkfun. You can actually get these displays of eBay quite readily and although the connector is quite tricky it is possible to make your own boards.
I haven't got any plans of making my own breakout boards for this.

**Comment by q2dg** [comment]
Oook, thanks!
I close the issue, then
